- title: "FORGE '25 Industry Track PC"
  date: 2025-04-29
  service-type: "conference-reviewer"
- title: "TOSEM Reviewer"
  date: 2024-12-30
  service-type: "journal-reviewer"
- title: "ESE Reviewer"
  date: 2025-01-01
  service-type: "journal-reviewer"
