- title: "ACM Transactions on Software Engineering and Methodology"
  shortname: TOSEM
  date: 2026-07-24
  venue-type: "journal-reviewer"
  url: "https://dl.acm.org/journal/tosem"
- title: "Empirical Software Engineering"
  shortname: ESE
  date: 2026-06-22
  venue-type: "journal-reviewer"
  url: "https://link.springer.com/journal/10664"
- title: "Fourth International Workshop on Software Vulnerability Management"
  shortname: SVM'26
  date: 2026-04-18
  venue-type: "conference-pc"
  url: "https://conf.researchr.org/home/icse-2026/svm-2026"
- title: "ACM Transactions on Software Engineering and Methodology"
  shortname: TOSEM
  date: 2026-03-30
  venue-type: "journal-reviewer"
  url: "https://dl.acm.org/journal/tosem"
- title: "ACM Transactions on Software Engineering and Methodology"
  shortname: TOSEM
  date: 2026-03-13
  venue-type: "journal-reviewer"
  url: "https://dl.acm.org/journal/tosem"
- title: "ACM Transactions on Software Engineering and Methodology"
  shortname: TOSEM
  date: 2025-12-15
  venue-type: "journal-reviewer"
  url: "https://dl.acm.org/journal/tosem"
- title: "ACM Transactions on Software Engineering and Methodology"
  shortname: TOSEM
  date: 2025-09-04
  venue-type: "journal-reviewer"
  url: "https://dl.acm.org/journal/tosem"
- title: "Ideas, Visions and Reflections Track, ACM International Conference on the Foundations of Software Engineering"
  shortname: FSE'25 IVR
  date: 2025-06-23
  venue-type: "conference-pc"
  url: "https://conf.researchr.org/track/fse-2025/fse-2025-ideas-visions-and-reflections"
- title: "ACM International Conference on AI Foundation Models and Software Engineering"
  shortname: FORGE'25
  date: 2025-04-27
  venue-type: "conference-pc"
  url: "https://conf.researchr.org/home/forge-2025"
- title: "Empirical Software Engineering"
  shortname: ESE
  date: 2024-12-30
  venue-type: "journal-reviewer"
  url: "https://link.springer.com/journal/10664"
- title: "Transactions on Information Forensics and Security"
  shortname: TIFS
  date: 2023-12-18
  venue-type: "journal-reviewer"
  url: "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10206"
